Embed MobilePayKit as a local Swift Package
Automattic/MobilePay-Apple pull request #1
Opened 2021-07-19 15:39 UTC by momo-ozawa

## Description

This PR adds the **StoreKit stack** and **embeds MobilePayKit as a local Swift package**. This lays the groundwork for developing the MobilePayKit library.

- Resolves https://github.com/wordpress-mobile/WordPress-iOS/issues/16862
- Resolves https://github.com/wordpress-mobile/WordPress-iOS/issues/16865

https://user-images.githubusercontent.com/6711616/126185663-4e34c2b8-3781-4c25-8f71-981be11ed1f1.mov

## Note

- Not yet implemented: a button on the PurchasableContentDetail view that consumes the purchased consumable
- I may rewrite the view logic in Swift (instead of SwiftUI)

## How to test

1. Go to Edit Scheme > Run > Options > StoreKit Configuration
2. Choose `Configuration.storekit`
3. Run the iOS app
4. Tap on Rocket Fuel to purchase
5. Tap Confirm
6. Tap OK
7. On Xcode debugger menu, click on the Manage StoreKit Transactions menu item (See example below)

<img width="536" alt="Screen Shot 2021-07-19 at 16 29 19" src="https://user-images.githubusercontent.com/6711616/126186328-1bc968f4-8c18-45ad-84f1-b5033fc1cbe7.png">

8. ✅ There should be a record of Rocket Fuel being purchased (See example below)

<img width="747" alt="Screen Shot 2021-07-19 at 16 32 32" src="https://user-images.githubusercontent.com/6711616/126186582-3f76559e-7fe5-45ae-9068-2754883f6351.png">

2021-07-19 17:19 UTC, leandroalonso requested changes

2021-07-19 17:19 UTC, leandroalonso commented on MobilePayKit/Sources/MobilePayKit/PaymentQueueService.swift
> +//
You might want to remove all those headers from the project

2021-07-19 17:19 UTC, leandroalonso commented on Shared/Assets.xcassets/com.mobilepay.consumable.rocketfuel.imageset/Contents.json
> +      "filename" : "fire_emoji.png",
nit: can't this be added just like a plain text?

2021-07-19 17:19 UTC, leandroalonso commented on Shared/PaymentViewModel.swift
> +                guard let self = self else { return }
```suggestion
                guard let self = self else {
                  return
                }
```

Just to conform with our standards + removing the comment.

2021-07-19 17:19 UTC, leandroalonso commented on Shared/PaymentViewModel.swift
> +import StoreKit
I wonder if we should encapsulate `StoreKit` completely inside the library without the need for the app to import it or to know any of its concepts.

All the objects returned would be our own objects which means that any necessary changes to IAP flows would happen only on the library, not on the app.

We don't necessarily need to do that now, though. Thoughts?

2021-07-19 17:19 UTC, leandroalonso commented on Shared/PurchasableContent.swift
> +import StoreKit
Same as above.

2021-07-19 19:11 UTC, leandroalonso commented
The build for macOS doesn't work, but I assume this is not the focus of this PR?

2021-07-20 09:05 UTC, momo-ozawa commented on Shared/PaymentViewModel.swift
> +import StoreKit
I agree. I'll address this in a subsequent PR.

2021-07-20 09:25 UTC, momo-ozawa commented
> The build for macOS doesn't work, but I assume this is not the focus of this PR?

Yep, I'll focus on macOS on a different PR. 

If you comment out this line, the macOS app should build... but the UI needs a lot of work. I'll make a separate SwiftUI file for macOS in a separate PR.
https://github.com/Automattic/MobilePay-Apple/blob/eb0205274272cab34559b81511d39929a2b72ef3/Shared/ContentView.swift#L101-L103

2021-07-20 09:49 UTC, momo-ozawa commented on Shared/Assets.xcassets/com.mobilepay.consumable.rocketfuel.imageset/Contents.json
> +      "filename" : "fire_emoji.png",
Do you mean displaying the emoji as a plain text in a label, rather than an image asset?

I think this will change in the future anyway -- I'm just using the emoji pngs as a placeholder image for the time being.

2021-07-20 09:50 UTC, momo-ozawa commented on MobilePayKit/Sources/MobilePayKit/PaymentQueueService.swift
> +//
Fixed! 5781ff3

2021-07-20 09:51 UTC, momo-ozawa commented on Shared/PaymentViewModel.swift
> +                guard let self = self else { return }
Fixed! 187c56e

2021-07-20 12:12 UTC, momo-ozawa commented on Shared/PaymentViewModel.swift
> +import StoreKit
Fixed in https://github.com/Automattic/MobilePay-Apple/pull/2

2021-07-20 13:25 UTC, leandroalonso commented on Shared/Assets.xcassets/com.mobilepay.consumable.rocketfuel.imageset/Contents.json
> +      "filename" : "fire_emoji.png",
Yes and ok!

2021-07-20 13:28 UTC, leandroalonso approved these changes

2021-07-20 13:40 UTC, merged