Inject oAuthToken and bundleId
Automattic/MobilePay-Apple pull request #11
Opened 2021-08-05 16:19 UTC by momo-ozawa

## Description
This PR injects the bearer token and the bundle id from the app into MobilePayKIt.

## Changes
- Added a `MobilePayKitConfiguration` struct that holds the bearer token and the bundle id
- Renamed `PaymentManager` to `MobilePayKit`
- Added `MobilePayKitTests`

## How to test

### Running tests
1. Run MobilePayKitTests test target
2. ✅ Tests should pass

### Running the app

1. Configure the bearer token in `ProductListViewModel`
2. Run the iOS app
3. Purchase the product by tapping on it
4. Tap Confirm
5. Tap OK
6. On Xcode debugger menu, click on the Manage StoreKit Transactions menu item 
7. ✅ There should be a record of a product being purchased (See example below)

<img width="747" alt="Screen Shot 2021-07-19 at 16 32 32" src="https://user-images.githubusercontent.com/6711616/126186582-3f76559e-7fe5-45ae-9068-2754883f6351.png">

2021-08-05 17:25 UTC, leandroalonso requested changes

2021-08-05 17:25 UTC, leandroalonso commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
I'm a little bit confused, we're applying the singleton pattern here but all the methods are static/class and they can be called directly.

I'd prefer to not have `class`/`static` method, since this will guarantee that if the object was created, a configuration was given, and you won't need to check for its existence.

It will also force people to inject this in order to use it, which I really like. :P

2021-08-05 17:25 UTC, leandroalonso commented on Source/Services/AppStoreService.swift
> +    private let iapService: InAppPurchasesService?
Given in the constructor we assign this property a default value in case `nil` was given, there's no reason for this to be `Optional`.

2021-08-05 18:07 UTC, emilylaguna commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
I agree with @leandroalonso.

2021-08-06 11:43 UTC, momo-ozawa commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
So my thinking was this:

1. I wanted to create a `sharedInstance`, because there should only be one instance of `MobilePayKit`
2. I wanted to inject the configs, but keep the init method private
3. I wanted to make it easier to call the MobilePayKit methods, so I made wrapper class methods which ultimately call the methods on the `sharedInstance`

To address point 2, I added a class method `configure`, which MUST be called before calling any other MobilePayKit methods. Otherwise, you get a fatalError. I could add an assert statement to make this more clear.

```
    public class func fetchProducts(completion: @escaping FetchCompletionCallback) {
        assert(configuration != nil, "MobilePayKit.configure(configuration:) must be called before calling this method")
        sharedInstance.fetchProducts(completion: completion)
    }
```

About point 3 --  I thought it would be nicer to be able to call `MobilePayKit.method` as opposed to `MobilePayKit.sharedInstance.method`, and the wrapper class methods are calling the instance methods anyway under the hood.

I'm more than happy to inject the config via init, I just wanted to clarify the approach I took. 

Let me know your thoughts! 😄

2021-08-06 13:15 UTC, leandroalonso commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
Oh, I see.

In this case, I think you can rely just on the `sharedInstance` and let the user to deal with how they want to use it. Take for example `UserDefaults.standard`, in a lot of places we assign this to a var to make it easier to use, instead of calling the `default` over and over.

The static methods favor inline use, which in turn makes testing almost impossible. Getting rid of them would probably solve the issues and prevent that. :)

2021-08-06 13:46 UTC, nikola-milicevic commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
@momo-ozawa I do understand the intent, and I like it, but I agree with @leandroalonso about mentioned shortcomings, so I vote for direct use of `shared` (not `sharedInstance` 😁) and injected dependencies.

2021-08-06 14:13 UTC, momo-ozawa commented on Source/MobilePayKit.swift
> +    private static let sharedInstance = MobilePayKit()
Thanks for the feedback y'all! Will update this PR shortly.

2021-08-06 16:14 UTC, momo-ozawa commented on Source/Services/AppStoreService.swift
> +    private let iapService: InAppPurchasesService?
Fixed! 57c03e8

2021-08-06 16:44 UTC, leandroalonso approved these changes

2021-08-09 09:10 UTC, merged