Encapsulate StoreKit inside MobilePayKit
Automattic/MobilePay-Apple pull request #2
Opened 2021-07-20 10:43 UTC by momo-ozawa

## Description

This PR encapsulates `StoreKit` completely inside the `MobilePayKit` library. This means that any app using `MobilePayKit` won't need to directly interface with `StoreKit`.

Ref: https://github.com/Automattic/MobilePay-Apple/pull/1#discussion_r672486337

## How to test

1. Go to Edit Scheme > Run > Options > StoreKit Configuration
2. Choose `Configuration.storekit`
3. Run the iOS app
4. Tap on Rocket Fuel to purchase
5. Tap Confirm
6. Tap OK
7. On Xcode debugger menu, click on the Manage StoreKit Transactions menu item (See example below)

<img width="536" alt="Screen Shot 2021-07-19 at 16 29 19" src="https://user-images.githubusercontent.com/6711616/126186328-1bc968f4-8c18-45ad-84f1-b5033fc1cbe7.png">

8. ✅ There should be a record of Rocket Fuel being purchased (See example below)

<img width="747" alt="Screen Shot 2021-07-19 at 16 32 32" src="https://user-images.githubusercontent.com/6711616/126186582-3f76559e-7fe5-45ae-9068-2754883f6351.png">

2021-07-20 13:40 UTC, leandroalonso requested changes

2021-07-20 13:40 UTC, leandroalonso commented on MobilePayKit/Sources/MobilePayKit/PaymentViewModel.swift
> +public class PaymentViewModel: NSObject, ObservableObject {
Are you planning on adding unit tests for this on a future PR?

2021-07-20 13:40 UTC, leandroalonso commented on MobilePayKit/Sources/MobilePayKit/PaymentViewModel.swift
> +public class PaymentViewModel: NSObject, ObservableObject {
We don't necessarily need to change that right now but I wonder if we should call it `PaymentViewModel`.

Thiking about the library, we would need an entity that:

1. Return products
2. "Buy" products
3. Return states/errors
4. Can restore a purchase

So maybe naming `PaymentManager` would make sense?

Then, in the app, the user can have a `PaymentViewModel` that connects with this entity.

2021-07-20 13:56 UTC, momo-ozawa commented on MobilePayKit/Sources/MobilePayKit/PaymentViewModel.swift
> +public class PaymentViewModel: NSObject, ObservableObject {
@leandroalonso 

> Are you planning on adding unit tests for this on a future PR?

Yes, definitely! I will make a separate PR with tests.

> Thiking about the library, we would need an entity that:
> 
>     Return products
>     "Buy" products
>     Return states/errors
>     Can restore a purchase
> 
> So maybe naming PaymentManager would make sense?
> 
> Then, in the app, the user can have a PaymentViewModel that connects with this entity.

Yeah, PaymentManager makes sense. I'll make changes to this current PR.

2021-07-21 11:02 UTC, momo-ozawa commented
@leandroalonso `PaymentViewModel` is now defined in the app, and is hooked up to MobilePayKit's `PaymentManager`.

2021-07-21 14:06 UTC, leandroalonso approved these changes

2021-07-21 14:29 UTC, merged