Add initial networking layer
Automattic/MobilePay-Apple pull request #5
Opened 2021-07-29 17:28 UTC by momo-ozawa

## Description

Resolves https://github.com/wordpress-mobile/WordPress-iOS/issues/16863

This PR adds the initial networking layer:

- Added `InAppPurchasesService` to call the fetch product skus / create order endpoints
- Added initial `InAppPurchasesServiceTests`
- Added `InAppPurchasesAPIRouter` to organize the endpoints 
- Added Alamofire as a package dependency

## Notes
- I will add more tests to InAppPurchasesService in a later PR

## How to test 

1. Go to Edit Scheme > Run > Options > StoreKit Configuration
2. Choose `Configuration.storekit`
3. Run the iOS app
4. Tap on Rocket Fuel to purchase
5. Tap Confirm
6. Tap OK
7. On Xcode debugger menu, click on the Manage StoreKit Transactions menu item (See example below)

<img width="536" alt="Screen Shot 2021-07-19 at 16 29 19" src="https://user-images.githubusercontent.com/6711616/126186328-1bc968f4-8c18-45ad-84f1-b5033fc1cbe7.png">

8. ✅ There should be a record of Rocket Fuel being purchased (See example below)

<img width="747" alt="Screen Shot 2021-07-19 at 16 32 32" src="https://user-images.githubusercontent.com/6711616/126186582-3f76559e-7fe5-45ae-9068-2754883f6351.png">

2021-07-29 18:15 UTC, leandroalonso commented
@momo-ozawa These tests are failing:

`testPaymentQueueUpdatedTransactions_WhenTransactionStateIsPurchased_CallsFinishTransaction`
`testPaymentQueueUpdatedTransactions_WhenTransactionStateIsRestored_CallsFinishTransaction`

2021-07-29 19:19 UTC, emilylaguna requested changes
Hiya! Overall this works really well! I left a couple comments below.

In addition the tests that are failing, I found the macOS example doesn't build because `navigationBarItems` is for iOS only. 

Also, I'm unsure we need to use Alamofire since the requests themselves are pretty simple, and we should be able to use URLSession's instead. Unless there was a specific reason you chose to use AF?

2021-07-29 19:19 UTC, emilylaguna commented on MobilePayKit/Sources/MobilePayKit/Services/AppStore/AppStoreService.swift
> +            price: Int(truncating: product.price),
The value of the price should be in cents, if the price is `5.99` then it should be converted to: `599`.

In theory this should work unless there's a better way: 

`Int(price.floatValue * 100)`

2021-07-29 19:19 UTC, emilylaguna commented on MobilePayKit/Sources/MobilePayKit/Services/AppStore/AppStoreService.swift
> +            print("Could not find app store receipt")
Should we handle the returns as errors?

2021-07-29 19:54 UTC, leandroalonso commented on MobilePay-Apple.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "package": "Alamofire",
@momo-ozawa there's any special reason why we need `Alamofire`?

I think it would be good to keep this library without dependencies and as much light as possible. Nowadays `URLSession` is very powerful so I think we can go with it.

This can be refactored on a future PR though.

2021-07-30 10:30 UTC, momo-ozawa commented on MobilePayKit/Sources/MobilePayKit/Services/AppStore/AppStoreService.swift
> +            print("Could not find app store receipt")
Yes! I'm thinking of creating a separate PR for error handling. 

I think this PR might get big if I changed the CompletionCallbacks from `(T) -> Void` to something like `(Result<T, Error>) -> Void`.

2021-07-30 12:42 UTC, leandroalonso commented
@momo-ozawa as we talked, let's ignore the failing tests for now and then we can get back to those later.

2021-07-30 13:05 UTC, momo-ozawa commented
@leandroalonso @emilylaguna 
I added a separate task for the macOS build on the project issue.

I'll be removing Alamofire in favor of URLSession in my next PR 🙇‍♀️

2021-07-30 13:06 UTC, momo-ozawa commented on MobilePayKit/Sources/MobilePayKit/Services/AppStore/AppStoreService.swift
> +            price: Int(truncating: product.price),
Fixed. cd1fb1f

Thank you for updating the API docs as well! 🙇‍♀️

2021-07-30 15:11 UTC, emilylaguna commented on MobilePayKit/Sources/MobilePayKit/Services/AppStore/AppStoreService.swift
> +            print("Could not find app store receipt")
Makes sense to me!

2021-07-30 15:11 UTC, emilylaguna approved these changes
LGTM! 🚀

2021-08-02 15:28 UTC, momo-ozawa commented
Closing this PR due to merge conflicts -- I will create a new PR!

2021-08-02 15:28 UTC, closed without merging